"
## Relations
======================

### Parents
| Relation | Origin | Opposite | Type | Comment |
|---|
| `parentAsPatternTarget` | `FASTPyTAsPatternTarget` | `target` | `FASTPyAsPattern` | |



"
Class {
	#name : 'FASTPyTuple',
	#superclass : 'FASTPyCollectionInitializer',
	#traits : 'FASTPyTAsPatternTarget',
	#classTraits : 'FASTPyTAsPatternTarget classTrait',
	#category : 'FAST-Python-Model-Entities',
	#package : 'FAST-Python-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTPyTuple class >> annotation [

	<FMClass: #Tuple super: #FASTPyCollectionInitializer>
	<package: #'FAST-Python-Model'>
	<generated>
	^ self
]
