"
## Relations
======================

### Parents
| Relation | Origin | Opposite | Type | Comment |
|---|
| `parentClassPattern` | `FASTPyTClassPatternElement` | `elements` | `FASTPyClassPattern` | |



"
Class {
	#name : 'FASTPyKeywordPattern',
	#superclass : 'FASTPyEntity',
	#traits : 'FASTPyTClassPatternElement',
	#classTraits : 'FASTPyTClassPatternElement classTrait',
	#category : 'FAST-Python-Model-Entities',
	#package : 'FAST-Python-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTPyKeywordPattern class >> annotation [

	<FMClass: #KeywordPattern super: #FASTPyEntity>
	<package: #'FAST-Python-Model'>
	<generated>
	^ self
]
