"
## Relations
======================

### Parents
| Relation | Origin | Opposite | Type | Comment |
|---|
| `parentSplat` | `FASTPyTCanBeSplatExpression` | `expression` | `FASTPyCollectionSplat` | |



"
Class {
	#name : 'FASTPyDictionary',
	#superclass : 'FASTPyCollectionInitializer',
	#category : 'FAST-Python-Model-Entities',
	#package : 'FAST-Python-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTPyDictionary class >> annotation [

	<FMClass: #Dictionary super: #FASTPyCollectionInitializer>
	<package: #'FAST-Python-Model'>
	<generated>
	^ self
]
