"
## Relations
======================

### Children
| Relation | Origin | Opposite | Type | Comment |
|---|
| `target` | `FASTPyTSplatParameter` | `parentSplatParameter` | `FASTPyTSplatParameterTarget` | |



"
Class {
	#name : 'FASTPyListSplatParameter',
	#superclass : 'FASTPyParameter',
	#traits : 'FASTPyTSplatParameter',
	#classTraits : 'FASTPyTSplatParameter classTrait',
	#category : 'FAST-Python-Model-Entities',
	#package : 'FAST-Python-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTPyListSplatParameter class >> annotation [

	<FMClass: #ListSplatParameter super: #FASTPyParameter>
	<package: #'FAST-Python-Model'>
	<generated>
	^ self
]
